#!/usr/bin/env bash
# This script is displaying numbers  from 1-100
for i  in {1..100..1}
do
    if [ $((i % 15)) -eq  0 ]
    then
	echo  "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi
done
