#!/usr/bin/env bash
# This script displays best school
# displays bad luck for the  4th loop iteration
# displays goodluck for the 8th loop iteration
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
